{% set name = "outcome" %}
{% set version = "1.0.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "fc7822068ba7dd0fc2532743611e8a73246708d3564e29a39f93d6ab3701b66f" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  host:
    - pip
  run:
    - python
    - attrs  >=19.2.0

test:
  imports:
    - outcome

about:
  home: https://github.com/python-trio/outcome
  license: MIT
  license_family: MIT
  license_file: 'LICENSE'
  summary: Capture the outcome of Python function calls.
  description: "Capture the outcome of Python function calls."

extra:
  recipe-maintainers:
    - nicoddemus
