{% set name = "outcome" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5427e7d3c48bcb9d383e08ba057359b570c6118d0e640da5baeb0e298502a4b2

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed
  skip: True  # [py<37]

requirements:
  host:
    - pip
    - setuptools
    - wheel
    - python
  run:
    - python
    - attrs  >=19.2.0

test:
  imports:
    - outcome
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/python-trio/outcome
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Capture the outcome of Python function calls.
  description: Capture the outcome of Python function calls.

extra:
  recipe-maintainers:
    - nicoddemus
