travis:
  secure:
    BINSTAR_TOKEN: GOhC8gx5nNwmCOWHkKARuRqiIbZCNTf/3F7A+eRcEnCa/3Uk0RpRod/6UkaYvAmUs+Xx40XH+CdGYRuamTDi+vIwWrgArzL8mBK3thvOWUeT+BLhzZ5bZfOljvew1YVmWjjCsGPnNrv+K6CkOb14KZreJ3zfMhPPA5PL5YZ8yc0DsM1cixJ0MydaFNzGdzHT0vM0qA3msGdz9eGuDUEZ8xnjRCyiB2D1Yv2ANoFer5+6RdztNzBVVKYFSdEOfXnq3BunLwOvdAFsh5vE/4HjydaVbZDo74ShPVZlSUDLF+oiGZ9+A8AdCOX0hlOkm80wqsvn5MwZg6yb2YilSLoP7VsB33pO/UnqyvTEVvrsw2WB+b9U4TSDNHnzl91Fuz0pEg54dzUAiMseMAQqxFuQsdN7QVo40L1CDVMUZgMR8vkEE5IOoDtfCR+bhKLck7MJWooHkFrhKAJZ9wGwcTXL5y8IICNfRJT5m67+x4h1uDa8nVvFMKx2v7ufkAQvHnJhUo/kRKZe9xPl5Hp+cMAQ70feKuPG1G0MaPsstYod/Xsh5TpPKYlbQcBOZ4QeNT6d5o2OxAq/4EYrLgeKD7t5kkfQ+Y3ZznGA+nXz9/qmRe0837GmkGlfJ87avePolP/orsWe6BkOxnrl/zSdV6iTeaAUIIoahVKV2XSCl4QMwNA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
