travis:
  secure:
    BINSTAR_TOKEN: jRUPqMQWMxULMxCqiIWbn/ZgVMWVDPvlAOfVLzK/L4cP5TJVQgIgfVNHRyRE0JRgGMKWM8VuE7jXaUj2cs+2kAsYx3T5IrtrnN5pTgn6GnXUaPoebi3w/9xrKY00gkaZTAlifjznRyETxmMJDMpAw/MMNp/B4Ydkp2B7oKfa/0ZSNYR0Aynoz6XqM4JD2Pi8Hs+1B1NMSVRWQ6+Qn9Pcfzlr2L8fpTR3qxI4v5mjXPqWKqFDrBLvri0+vE28wJDxd3VAvxA0yF4nP9IGIfNuHrwj7KD+Fyiwj0D7h+Mklz0hNAET0g+6C59I/4ibltARxci07e5iS+v/JqXGZaoCvyzaZ5xVe4p3jrerYzSb/pp63Kfco9pmcEPDuqOlCWecQqX+u56jXjej7wXPB0kCyfQgQBpuQegCgprOY0JotfQAmJiJIIs4Mg1wcqpO0+d11+Bc0X9aHXsZV32JvmMwedREvYkL9TDlKBhbGLjjjCYbRkQxNguo+M7B/6rWcopIo3dp3TsimVmkKY3RLziIzSo9HODIhhObaVdVtUhJv6umaTtm5B2xryexgpijpoKSV4r8Vw97w6HxFQFJLXu+ARrUHZ4MB6qpFJYl1qm4hZEcWZSIyU0DBmta9fwCY8CHvo4zFZNe0s37+ZrNYL9b4unYpLh2pVCwI5irr1F/K4g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
